### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by teomaragakis** [ediamin/wp-bootstrap-comment-walker#1]
I included the walker and added the initialization to the comments function, but it doesn't seem to work. Has this been tested in latest versions of Wordpress?

**Comment by ediamin** [comment]
Yes, it works with the latest WordPress (v 4.3.1). Do you see any kind of error? Did you include bootstrap css?

**Comment by teomaragakis** [comment]
No error. BS CSS is included. I don’t get the HTML output for media list so it’s just the standard HTML without a walker.

**Comment by ediamin** [comment]
OK. Did you add the html5 support for comment list? If not add this code in your functions.php

`add_theme_support( 'html5', array( 'comment-list' ) );`

**Comment by teomaragakis** [comment]
That worked! Had no idea about this. I'd add it to the README if I were you. Thanks a lot!

**Comment by ediamin** [comment]
Great! I'll update the README. Thanks.
